app:
  name: "Moon API"
  version: "1.0.0"
  port: 8080
  mode: "debug" # debug, release

database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  name: "moon_db"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"

jwt:
  secret: "$2a$12$IDZNQL7K/7DCS5XaRNlnjeJK4RhRuDvHkHll.Lmyi8HGBnC4GClPS"
  expires_in: 24 # hours

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

logger:
  level: "info" # debug, info, warn, error
  format: "json"
